apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: personapi
  name: personapi
  namespace: spinnaker-system
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: personapi
  template:
    metadata:
      labels:
        app: personapi
    spec:
      containers:
      - image: garreeoke/person-api:773
        imagePullPolicy: Always
        name: personapi
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
